//AUTH CONSTANTS

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_MAIL_REQUEST = 'USER_MAIL_REQUEST';
export const USER_MAIL_SUCCESS = 'USER_MAIL_SUCCESS';
export const USER_MAIL_FAILURE = 'USER_MAIL_FAILURE';

export const USER_RESET_REQUEST = 'USER_RESET_REQUEST';
export const USER_RESET_SUCCESS = 'USER_RESET_SUCCESS';
export const USER_RESET_FAILURE = 'USER_RESET_FAILURE';

export const USER_CHANGE_PASS_REQUEST = 'USER_CHANGE_PASS_REQUEST';
export const USER_CHANGE_PASS_SUCCESS = 'USER_CHANGE_PASS_SUCCESS';
export const USER_CHANGE_PASS_FAILURE = 'USER_CHANGE_PASS_FAILURE';



//ROLE BASED CONSTATNTS
export const USER_ADD_REQUEST = 'USER_ADD_REQUEST';
export const USER_ADD_SUCCESS = 'USER_ADD_SUCCESS';
export const USER_ADD_FAILURE = 'USER_ADD_FAILURE';

export const USER_FETCH_ROLE_REQUEST = 'USER_FETCH_ROLE_REQUEST';
export const USER_FETCH_ROLE_SUCCESS = 'USER_FETCH_ROLE_SUCCESS';
export const USER_FETCH_ROLE_FAILURE = 'USER_FETCH_ROLE_FAILURE';


export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAILURE = 'USER_DELETE_FAILURE';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';




//STATUS BASED CONSTATNTS
export const USER_STATUS_REQUEST = 'USER_STATUS_REQUEST';
export const USER_STATUS_SUCCESS = 'USER_STATUS_SUCCESS';
export const USER_STATUS_FAILURE = 'USER_STATUS_FAILURE';

export const USER_STATUS_FOR_REQUEST = 'USER_STATUS_FOR_REQUEST';
export const USER_STATUS_FOR_SUCCESS = 'USER_STATUS_FOR_SUCCESS';
export const USER_STATUS_FOR_FAILURE = 'USER_STATUS_FOR_FAILURE';

export const USER_STATUS_CREATE_REQUEST = 'USER_STATUS_CREATE_REQUEST';
export const USER_STATUS_CREATE_SUCCESS = 'USER_STATUS_CREATE_SUCCESS';
export const USER_STATUS_CREATE_FAILURE = 'USER_STATUS_CREATE_FAILURE';

export const USER_STATUS_UPDATE_REQUEST = 'USER_STATUS_UPDATE_REQUEST';
export const USER_STATUS_UPDATE_SUCCESS = 'USER_STATUS_UPDATE_SUCCESS';
export const USER_STATUS_UPDATE_FAILURE = 'USER_STATUS_UPDATE_FAILURE';

export const USER_STATUS_DELETE_REQUEST = 'USER_STATUS_DELETE_REQUEST';
export const USER_STATUS_DELETE_SUCCESS = 'USER_STATUS_DELETE_SUCCESS';
export const USER_STATUS_DELETE_FAILURE = 'USER_STATUS_DELETE_FAILURE';


//PROPERTY BASED CONSTATNTS

export const PROPERTY_CREATE_REQUEST = 'PROPERTY_CREATE_REQUEST';
export const PROPERTY_CREATE_SUCCESS = 'PROPERTY_CREATE_SUCCESS';
export const PROPERTY_CREATE_FAILURE = 'PROPERTY_CREATE_FAILURE';


export const PROPERTY_DELETE_REQUEST = 'PROPERTY_DELETE_REQUEST';
export const PROPERTY_DELETE_SUCCESS = 'PROPERTY_DELETE_SUCCESS';
export const PROPERTY_DELETE_FAILURE = 'PROPERTY_DELETE_FAILURE';

export const PROPERTY_UPDATE_REQUEST = 'PROPERTY_UPDATE_REQUEST';
export const PROPERTY_UPDATE_SUCCESS = 'PROPERTY_UPDATE_SUCCESS';
export const PROPERTY_UPDATE_FAILURE = 'PROPERTY_UPDATE_FAILURE';

// export const USER_STATUS_UPDATE_REQUEST = 'USER_STATUS_UPDATE_REQUEST';
// export const USER_STATUS_UPDATE_SUCCESS = 'USER_STATUS_UPDATE_SUCCESS';
// export const USER_STATUS_UPDATE_FAILURE = 'USER_STATUS_UPDATE_FAILURE';

// export const USER_STATUS_DELETE_REQUEST = 'USER_STATUS_DELETE_REQUEST';
// export const USER_STATUS_DELETE_SUCCESS = 'USER_STATUS_DELETE_SUCCESS';
// export const USER_STATUS_DELETE_FAILURE = 'USER_STATUS_DELETE_FAILURE';


//PROPERTY BASED CONSTATNTS

export const PROPERTY_TYPE_ADD_REQUEST = 'PROPERTY_TYPE_ADD_REQUEST';
export const PROPERTY_TYPE_ADD_SUCCESS = 'PROPERTY_TYPE_ADD_SUCCESS';
export const PROPERTY_TYPE_ADD_FAILURE = 'PROPERTY_TYPE_ADD_FAILURE';

export const PROPERTY_TYPE_GET_REQUEST = 'PROPERTY_TYPE_GET_REQUEST';
export const PROPERTY_TYPE_GET_SUCCESS = 'PROPERTY_TYPE_GET_SUCCESS';
export const PROPERTY_TYPE_GET_FAILURE = 'PROPERTY_TYPE_GET_FAILURE';

export const PROPERTY_TYPE_UPDATE_REQUEST = 'PROPERTY_TYPE_UPDATE_REQUEST';
export const PROPERTY_TYPE_UPDATE_SUCCESS = 'PROPERTY_TYPE_UPDATE_SUCCESS';
export const PROPERTY_TYPE_UPDATE_FAILURE = 'PROPERTY_TYPE_UPDATE_FAILURE';

export const PROPERTY_TYPE_DELETE_REQUEST = 'PROPERTY_TYPE_DELETE_REQUEST';
export const PROPERTY_TYPE_DELETE_SUCCESS = 'PROPERTY_TYPE_DELETE_SUCCESS';
export const PROPERTY_TYPE_DELETE_FAILURE = 'PROPERTY_TYPE_DELETE_FAILURE';

export const PROPERTY_FORM_REQUEST = "PROPERTY_FORM_REQUEST";
export const PROPERTY_FORM_SUCCESS = "PROPERTY_FORM_SUCCESS";
export const PROPERTY_FORM_FAILURE = "PROPERTY_FORM_FAILURE";

export const GET_AFFILIATE_APPROVE = "GET_AFFILIATE_APPROVE";
export const SUCCESS_AFFILIATE_APPROVE = "SUCCESS_AFFILIATE_APPROVE";
export const FAILURE_AFFILIATE_APPROVE =  "FAILURE_AFFILIATE_APPROVE";

export const GET_COLLEGE_LIST = "GET_COLLEGE_LIST";
export const SUCCESS_COLLEGE_LIST = "SUCCESS_COLLEGE_LIST";
export const FAILURE_COLLEGE_LIST = "FAILURE_COLLEGE_LIST";

export const PROPERTY_GALLERY_ADD_REQUEST = "PROPERTY_GALLERY_ADD_REQUEST"
export const PROPERTY_GALLERY_ADD_SUCCESS = "PROPERTY_GALLERY_ADD_SUCCESS"
export const PROPERTY_GALLERY_ADD_FAILURE = "PROPERTY_GALLERY_ADD_FAILURE"

export const GET_GALLERY_LIST = 'GET_GALLERY_LIST';
export const SUCCESS_GALLERY_LIST = 'SUCCESS_GALLERY_LIST';
export const FAILURE_GALLERY_LIST = 'FAILURE_GALLERY_LIST';

export const PROPERTY_TEAM_ADD_REQUEST = "PROPERTY_TEAM_ADD_REQUEST"
export const PROPERTY_TEAM_ADD_SUCCESS = "PROPERTY_TEAM_ADD_SUCCESS"
export const PROPERTY_TEAM_ADD_FAILURE = "PROPERTY_TEAM_ADD_FAILURE"

export const PROPERTY_TEAM_UPDATE_REQUEST = "PROPERTY_TEAM_UPDATE_REQUEST"
export const PROPERTY_TEAM_UPDATE_SUCCESS = "PROPERTY_TEAM_UPDATE_SUCCESS"
export const PROPERTY_TEAM_UPDATE_FAILURE = "PROPERTY_TEAM_UPDATE_FAILURE"

export const GET_TEAM_LIST = 'GET_TEAM_LIST';
export const SUCCESS_TEAM_LIST = 'SUCCESS_TEAM_LIST';
export const FAILURE_TEAM_LIST = 'FAILURE_TEAM_LIST';

export const GET_PLACEMENT_LIST = 'GET_PLACEMENT_LIST';
export const SUCCESS_PLACEMENT_LIST = 'SUCCESS_PLACEMENT_LIST';
export const FAILURE_PLACEMENT_LIST = 'FAILURE_PLACEMENT_LIST';

export const GET_ANNOUNCEMENT_LIST = 'GET_ANNOUNCEMENT_LIST';
export const SUCCESS_ANNOUNCEMENT_LIST = 'SUCCESS_ANNOUNCEMENT_LIST';
export const FAILURE_ANNOUNCEMENT_LIST = 'FAILURE_ANNOUNCEMENT_LIST';

export const GET_SCHOLARSHIP_LIST = 'GET_SCHOLARSHIP_LIST';
export const SUCCESS_SCHOLARSHIP_LIST = 'SUCCESS_SCHOLARSHIP_LIST';
export const FAILURE_SCHOLARSHIP_LIST = 'FAILURE_SCHOLARSHIP_LIST';

export const GET_LOAN_LIST = 'GET_LOAN_LIST';
export const SUCCESS_LOAN_LIST = 'SUCCESS_LOAN_LIST';
export const FAILURE_LOAN_LIST = 'FAILURE_LOAN_LIST';

export const GET_ADMISSION_PROCESS_LIST = 'GET_ADMISSION_PROCESS_LIST';
export const SUCCESS_ADMISSION_PROCESS_LIST = 'SUCCESS_ADMISSION_PROCESS_LIST';
export const FAILURE_ADMISSION_PROCESS_LIST = 'FAILURE_ADMISSION_PROCESS_LIST';


export const PROPERTY_PLACEMENT_ADD_REQUEST = "PROPERTY_PLACEMENT_ADD_REQUEST";
export const PROPERTY_PLACEMENT_ADD_SUCCESS = "PROPERTY_PLACEMENT_ADD_SUCCESS";
export const PROPERTY_PLACEMENT_ADD_FAILURE = "PROPERTY_PLACEMENT_ADD_FAILURE";

export const PROPERTY_PLACEMENT_UPDATE_REQUEST = "PROPERTY_PLACEMENT_UPDATE_REQUEST";
export const PROPERTY_PLACEMENT_UPDATE_SUCCESS = "PROPERTY_PLACEMENT_UPDATE_SUCCESS";
export const PROPERTY_PLACEMENT_UPDATE_FAILURE = "PROPERTY_PLACEMENT_UPDATE_FAILURE";

export const PROPERTY_LOAN_ADD_REQUEST = "PROPERTY_LOAN_ADD_REQUEST";
export const PROPERTY_LOAN_ADD_SUCCESS = "PROPERTY_LOAN_ADD_SUCCESS";
export const PROPERTY_LOAN_ADD_FAILURE = "PROPERTY_LOAN_ADD_FAILURE";

export const PROPERTY_LOAN_UPDATE_REQUEST = "PROPERTY_LOAN_UPDATE_REQUEST";
export const PROPERTY_LOAN_UPDATE_SUCCESS = "PROPERTY_LOAN_UPDATE_SUCCESS";
export const PROPERTY_LOAN_UPDATE_FAILURE = "PROPERTY_LOAN_UPDATE_FAILURE";


export const PROPERTY_SCHOLARSHIP_ADD_REQUEST = "PROPERTY_SCHOLARSHIP_ADD_REQUEST";
export const PROPERTY_SCHOLARSHIP_ADD_SUCCESS = "PROPERTY_SCHOLARSHIP_ADD_SUCCESS";
export const PROPERTY_SCHOLARSHIP_ADD_FAILURE = "PROPERTY_SCHOLARSHIP_ADD_FAILURE";

export const PROPERTY_SCHOLARSHIP_UPDATE_REQUEST = "PROPERTY_SCHOLARSHIP_UPDATE_REQUEST";
export const PROPERTY_SCHOLARSHIP_UPDATE_SUCCESS = "PROPERTY_SCHOLARSHIP_UPDATE_SUCCESS";
export const PROPERTY_SCHOLARSHIP_UPDATE_FAILURE = "PROPERTY_SCHOLARSHIP_UPDATE_FAILURE";

export const PROPERTY_ADMISSION_PROCESS_ADD_REQUEST = "PROPERTY_ADMISSION_PROCESS_ADD_REQUEST";
export const PROPERTY_ADMISSION_PROCESS_ADD_SUCCESS = "PROPERTY_ADMISSION_PROCESS_ADD_SUCCESS";
export const PROPERTY_ADMISSION_PROCESS_ADD_FAILURE = "PROPERTY_ADMISSION_PROCESS_ADD_FAILURE";

export const PROPERTY_ADMISSION_PROCESS_UPDATE_REQUEST = "PROPERTY_ADMISSION_PROCESS_UPDATE_REQUEST";
export const PROPERTY_ADMISSION_PROCESS_UPDATE_SUCCESS = "PROPERTY_ADMISSION_PROCESS_UPDATE_SUCCESS";
export const PROPERTY_ADMISSION_PROCESS_UPDATE_FAILURE = "PROPERTY_ADMISSION_PROCESS_UPDATE_FAILURE";

export const PROPERTY_ANNOUNCEMENT_ADD_REQUEST = "PROPERTY_ANNOUNCEMENT_ADD_REQUEST";
export const PROPERTY_ANNOUNCEMENT_ADD_SUCCESS = "PROPERTY_ANNOUNCEMENT_ADD_SUCCESS";
export const PROPERTY_ANNOUNCEMENT_ADD_FAILURE = "PROPERTY_ANNOUNCEMENT_ADD_FAILURE";

export const PROPERTY_ANNOUNCEMENT_UPDATE_REQUEST = "PROPERTY_ANNOUNCEMENT_UPDATE_REQUEST";
export const PROPERTY_ANNOUNCEMENT_UPDATE_SUCCESS = "PROPERTY_ANNOUNCEMENT_UPDATE_SUCCESS";
export const PROPERTY_ANNOUNCEMENT_UPDATE_FAILURE = "PROPERTY_ANNOUNCEMENT_UPDATE_FAILURE";

export const PROPERTY_FAQS_ADD_REQUEST = "PROPERTY_FAQS_ADD_REQUEST";
export const PROPERTY_FAQS_ADD_SUCCESS = "PROPERTY_FAQS_ADD_SUCCESS";
export const PROPERTY_FAQS_ADD_FAILURE = "PROPERTY_FAQS_ADD_FAILURE";

export const PROPERTY_FAQS_UPDATE_REQUEST = "PROPERTY_FAQS_UPDATE_REQUEST";
export const PROPERTY_FAQS_UPDATE_SUCCESS = "PROPERTY_FAQS_UPDATE_SUCCESS";
export const PROPERTY_FAQS_UPDATE_FAILURE = "PROPERTY_FAQS_UPDATE_FAILURE";

export const GET_FAQS_LIST = 'GET_FAQS_LIST';
export const SUCCESS_FAQS_LIST = 'SUCCESS_FAQS_LIST';
export const FAILURE_FAQS_LIST = 'FAILURE_FAQS_LIST';

export const GET_QAS_LIST = 'GET_QAS_LIST';
export const SUCCESS_QAS_LIST = 'SUCCESS_QAS_LIST';
export const FAILURE_QAS_LIST = 'FAILURE_QAS_LIST';

export const CATEGORY_ADD_REQUEST = "CATEGORY_ADD_REQUEST";
export const CATEGORY_ADD_SUCCESS = "CATEGORY_ADD_SUCCESS";
export const CATEGORY_ADD_FAILURE = "CATEGORY_ADD_FAILURE";

export const CATEGORY_GET_REQUEST = 'CATEGORY_GET_REQUEST';
export const CATEGORY_GET_SUCCESS = 'CATEGORY_GET_SUCCESS';
export const CATEGORY_GET_FAILURE = 'CATEGORY_GET_FAILURE';

export const CATEGORY_DELETE_FAILURE="CATEGORY_DELETE_FAILURE";
export const CATEGORY_DELETE_REQUEST="CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS="CATEGORY_DELETE_FAILURE";

export const CATEGORY_UPDATE_REQUEST="CATEGORY_UPDATE_REQUEST";
export const CATEGORY_UPDATE_SUCCESS="CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAILURE="CATEGORY_UPDATE_FAILURE";

export const UNIVERSITY_COURSE_ADD_REQUEST = "UNIVERSITY_COURSE_ADD_REQUEST";
export const UNIVERSITY_COURSE_ADD_SUCCESS = "UNIVERSITY_COURSE_ADD_SUCCESS";
export const UNIVERSITY_COURSE_ADD_FAILURE = "UNIVERSITY_COURSE_ADD_FAILURE";


export const GET_UNIVERSITY_COURSE_LIST = 'GET_UNIVERSITY_COURSE_LIST';
export const SUCCESS_UNIVERSITY_COURSE_LIST = 'SUCCESS_UNIVERSITY_COURSE_LIST';
export const FAILURE_UNIVERSITY_COURSE_LIST = 'FAILURE_UNIVERSITY_COURSE_LIST';


